server:
  port: 8810

spring:
  application:
    name: consumer-zookeeper
  cloud:
    zookeeper:
      discovery:
        register: false
      connect-string: localhost:2181
      dependencies:
        - service-zookeeper:
          required: true
          path: /service-zookeeper
          loadBalancerType: ROUND_ROBIN
