server:
  port: 8810

spring:
  application:
    name: consumer-zookeeper
  cloud:
    zookeeper:
      discovery:
        register: false
      dependencies:
        service-zookeeper:
          required: true
          path: /service-zookeeper
      connect-string: localhost:2181


