server:
  port: 8800
spring:
  profiles:
    active: dev
  application:
    name: ereka-server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

---
spring:
  profiles: dev